services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authmotion_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "14333:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authmotion_api
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthMotionDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;

      # JWT & Google
      - JwtSettings__Secret=${JWT_SECRET}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}

      # Email (Unificado con EmailSettings y Username)
      - EmailSettings__Host=sandbox.smtp.mailtrap.io
      - EmailSettings__Port=2525
      - EmailSettings__Username=${MAILTRAP_USER}
      - EmailSettings__Password=${MAILTRAP_PASS}
      - EmailSettings__EnableSsl=true
      - EmailSettings__SenderEmail=noreply@authmotion.com
      - EmailSettings__SenderName=AuthMotion Security

volumes:
  sqlvolume:
