services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authmotion_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AuthMotion_Password123!
    ports:
      - "14333:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
